clear all
close all
clc

%---------------- EDEIR ------------------

% replicate column 4 of table 4.4
% make sure the results generated by the new model is consistent with the old results
dynare EDEIR

% turn off productivity shock and turn on interest rate shock
set_param_value('eta', 0);
set_param_value('sigma_mu', 0.012);

% set_param_value('eta', 0.0129);
% set_param_value('sigma_mu', 0.0);

% re-run the model
options_.irf = 20;
[info,oo_,options_,M_]=stoch_simul(M_,options_,oo_,var_list_);



%---------------- IDF --------------------

clear all
close all
clc
% replicate column 1 of table 4.4
% make sure the results generated by the new model is consistent with the old results
dynare IDF

% turn off productivity shock and turn on interest rate shock
set_param_value('sigma_tfp', 0);
set_param_value('sigma_mu',  0.012);

% set_param_value('sigma_tfp', 0.0129);
% set_param_value('sigma_mu',  0.0);

% re-run the model
options_.irf = 20; 
[info,oo_,options_,M_]=stoch_simul(M_,options_,oo_,var_list_);



